### ISSUE TITLE
project version in repo is not on fpm

### ISSUE THREAD

**Issue by idkjs** [SllyQ/bs-date-fns#8]
Why is the year below `1986` when passing in a unix time with year of `2019`?

```ocaml
let time = Js.Date.make();
Js.log2("time", time);

let getTime = time->Js.Date.getTime->int_of_float;
Js.log2("getTime", getTime);

let date = DateFns.fromUnixTime(getTime);
Js.log2("date", date);
```

logs:
```sh
time 2019-12-19T20:53:07.446Z

getTime 535789814

date 1986-12-24T06:30:14.000Z
```

Thank you, sir.

**Comment by SllyQ** [comment]
Hi, as the new date-fns version includes breaking changes, I wanted to include more long-overdue breaking changes with unflipping the methods. Now it's live on pre-release channel. You can try it out via `npm install bs-date-fns@next`. Any and all feedback is welcome.

About the issue you were experiencing. You ran into the problem because bucklescript int is 32 bit and `getTime` returns unix timestamp in milliseconds which makes it overflow. To help avoid such mistakes I made the new prerelease version `fromUnixTime` function take float instead of int as an argument.

With the new version this code behaves as expected
```
let time = Js.Date.make();
Js.log2("time", time);

let getTime = time->Js.Date.getTime;
Js.log2("getTime", getTime);

let date = DateFns.fromUnixTime(getTime /. 1000.);
Js.log2("date", date);
``` 

Closing the issue but if you have any questions feel free.
