### ISSUE TITLE
bindings to date-fns v2 don't seem to create the correct imports.

### ISSUE THREAD

**Issue by tcoopman** [SllyQ/bs-date-fns#9]
I'm running into an issue that bs-date-fns@next don't create correct imports. It seems a bit strange that this is the case as there are no issues about this yet. So maybe I'm doing something wrong, but here is what I found out:

According to the new docs (https://github.com/date-fns/date-fns/blob/master/docs/esm.md) the imports should now be written as:

```javascript
// Before
import * as format from 'date-fns/format'

// Now
import format from 'date-fns/format'
```

The current bindings generate an error. I've created a reproduction here: https://github.com/tcoopman/date-fns-bug-reproduction, the compiled output can be found here: https://github.com/tcoopman/date-fns-bug-reproduction/blob/master/src/Index.bs.js

Changing the binding from: `[@bs.module] external format: (Js.Date.t, string) => string = "date-fns/format";` to `[@bs.module "date-fns/format"] external format: (Js.Date.t, string) => string = "default";` fixes the problem (as described here: https://bucklescript.github.io/docs/en/import-export#import-an-es6-default-value)

**Comment by ashton** [comment]
I believe that this works just because the project uses webpack, In my setup, I'm using `moduleserve` for development, and it breaks because it don't recognizes the export as an es module, that way, the `default` property is undefined, and we get an error when calling the function: [](https://github.com/ashton/pet-manager)

![image](https://user-images.githubusercontent.com/95974/84194898-198fbc80-aa74-11ea-996e-660897147b16.png)

Maybe [this](https://github.com/BuckleScript/bucklescript.github.io/issues/46#issuecomment-390298167) has something to do with it, I don't have enough experience in reason to propose a PR to solve this, sorry :(
